name: srmobileapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.4+14

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # mic_stream: 0.6.2
  mic_stream: 
    path: ./PLUGINS/mic_stream
  flutter_audio_waveforms: 
    path: ./PLUGINS/flutter_audio_waveforms1.1.1.3/
  # quick_usb: 
  #   path: ./PLUGINS/quick_usb-0.4.0/

  # circular_buffer: 0.11.0    
  # flutter_webrtc: 0.9.9+hotfix.1
  # flutter_background: 1.1.0
  async: 2.10.0
  crypto: 3.0.2
  shared_preferences: 2.0.17
  path_provider: 2.0.12
  # flutter_wasm : 
  #   path: ./PLUGINS/wasm/flutter_wasm/

  alert_dialog: 1.0.1
  custom_pop_up_menu: 1.2.4
  another_xlider: 1.1.2
  dotted_line: 3.1.0
  
  
  # quick_usb: ^0.4.0  
  mfi: 
    path: ./PLUGINS/mfi
  # COMMENT FOR WEB
  usb_serial: 0.4.0
  flutter_libserialport: 0.3.0
  winaudio: 
    path: ./PLUGINS/winaudio
  desktop_window: 0.4.0
  nativec: 
    path: ./PLUGINS/nativec/
  gesture_x_detector: 1.1.1

  flutter:
    sdk: flutter
  # fps_widget: 1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  permission_handler: 10.2.0

  fialogs: 
    path: ./PLUGINS/fialogs
  localstorage: 4.0.0+1  
  firebase_core: 2.7.1

  flutter_form_builder: 7.7.0
  form_builder_validators: 8.4.0
  http: 0.13.5
  
  # is native device
  firebase_analytics: 10.1.5
  firebase_crashlytics: 3.0.16
  #firebase_messaging: 14.1.4
  firebase_performance: 0.9.0+15
  tutorial_coach_mark: 1.2.4
  device_info_plus: 8.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
    # - wasm/fib.wasm
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
