# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :distribute do
    build_app(
      workspace: "Runner.xcworkspace", 
      # xcargs: "-allowProvisioningUpdates",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.backyardbrains.srflutterios" => "SpikeRecorderFlutterPP",
        }
      },      
      output_directory: "../build/ios", 
      output_name: "sr-flutter.ipa", 
      scheme: "Runner")
    release = firebase_app_distribution(
      app: "1:62668804297:ios:2e1442d6910b0ba6523d18",
      ipa_path: "../build/ios/sr-flutter.ipa",
      testers: "djojokusumo.stevanus@gmail.com",
      release_notes: "Lots of amazing new features to test out!"
    )
  end
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
