// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLnWX82fGBHvQWIHqEU2qfqGGgJHmIFJI',
    appId: '1:62668804297:web:3fb6abbe2cfabf80523d18',
    messagingSenderId: '62668804297',
    projectId: 'webspikerecorder',
    authDomain: 'webspikerecorder.firebaseapp.com',
    storageBucket: 'webspikerecorder.appspot.com',
    measurementId: 'G-BK6NLYYL50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHms3OKjtGx6DwKhM_VrHy7nUUpRpmIi4',
    appId: '1:62668804297:android:2774634e3310c763523d18',
    messagingSenderId: '62668804297',
    projectId: 'webspikerecorder',
    storageBucket: 'webspikerecorder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4qNR5OWEggFND_54ns20g7xlHByQtvo',
    appId: '1:62668804297:ios:2e1442d6910b0ba6523d18',
    messagingSenderId: '62668804297',
    projectId: 'webspikerecorder',
    storageBucket: 'webspikerecorder.appspot.com',
    androidClientId: '62668804297-e5l5ghtojirdcfm8lj0idtaa4cptj3n0.apps.googleusercontent.com',
    iosClientId: '62668804297-mnl9lq4b30gl2qnhjb2a4ohfmkvkql35.apps.googleusercontent.com',
    iosBundleId: 'com.backyardbrains.srflutterios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj4qNR5OWEggFND_54ns20g7xlHByQtvo',
    appId: '1:62668804297:ios:948434efb4e92672523d18',
    messagingSenderId: '62668804297',
    projectId: 'webspikerecorder',
    storageBucket: 'webspikerecorder.appspot.com',
    androidClientId: '62668804297-e5l5ghtojirdcfm8lj0idtaa4cptj3n0.apps.googleusercontent.com',
    iosClientId: '62668804297-kniaql0kbi2a69o08uqolg69bck8m7h9.apps.googleusercontent.com',
    iosBundleId: 'com.backyardbrains.srfluttermac',
  );
}
