# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# import_plugins
default_platform(:android)

platform :android do
  desc "Firebase App Distribution"
  lane :distribute do
      build_android_app(build_type: 'Release',  print_command: true,)
      # build_android_app is a built-in fastlane action.
      release = firebase_app_distribution(
          app: "1:62668804297:android:2774634e3310c763523d18",
          android_artifact_type:"APK",
          android_artifact_path:"../build/app/outputs/apk/release/app-release.apk",
          testers: "djojokusumo.stevanus@gmail.com",
          release_notes: "Lots of amazing new features to test out!"
      )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
