/**
 * Skipped minification because the original files appears to be already minified.
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(d){var f=function(){};f.prototype=d;return new f};$jscomp.underscoreProtoCanBeSet=function(){var d={a:!0},f={};try{return f.__proto__=d,f.a}catch(h){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(d,f){d.__proto__=f;if(d.__proto__!==f)throw new TypeError(d+" is not extensible");return d}:null;
$jscomp.inherits=function(d,f){d.prototype=$jscomp.objectCreate(f.prototype);d.prototype.constructor=d;if($jscomp.setPrototypeOf){var h=$jscomp.setPrototypeOf;h(d,f)}else for(h in f)if("prototype"!=h)if(Object.defineProperties){var l=Object.getOwnPropertyDescriptor(f,h);l&&Object.defineProperty(d,h,l)}else d[h]=f[h];d.superClass_=f.prototype};
$jscomp.checkStringArgs=function(d,f,h){if(null==d)throw new TypeError("The 'this' value for String.prototype."+h+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+h+" must not be a regular expression");return d+""};$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,f,h){d!=Array.prototype&&d!=Object.prototype&&(d[f]=h.value)};
$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,f,h,l){if(f){h=$jscomp.global;d=d.split(".");for(l=0;l<d.length-1;l++){var n=d[l];n in h||(h[n]={});h=h[n]}d=d[d.length-1];l=h[d];f=f(l);f!=l&&null!=f&&$jscomp.defineProperty(h,d,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("String.prototype.codePointAt",function(d){return d?d:function(d){var f=$jscomp.checkStringArgs(this,null,"codePointAt"),l=f.length;d=Number(d)||0;if(0<=d&&d<l){d|=0;var n=f.charCodeAt(d);if(55296>n||56319<n||d+1===l)return n;d=f.charCodeAt(d+1);return 56320>d||57343<d?n:1024*(n-55296)+d+9216}}},"es6","es3");$jscomp.owns=function(d,f){return Object.prototype.hasOwnProperty.call(d,f)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(d,f){for(var h=1;h<arguments.length;h++){var l=arguments[h];if(l)for(var n in l)$jscomp.owns(l,n)&&(d[n]=l[n])}return d};$jscomp.polyfill("Object.assign",function(d){return d||$jscomp.assign},"es6","es3");
(function(d,f){"object"===typeof exports&&"undefined"!==typeof module?f(exports):"function"===typeof define&&define.amd?define(["exports"],f):(d=d||self,f(d.wavefileParser={}))})(this,function(d){function f(a,b,c,g){g=void 0===g?a.length:g;if(g%b)throw Error("Bad buffer length.");for(c=void 0===c?0:c;c<g;c+=b){var e=a,d=b,f=c;d--;for(var k=0;k<d;k++){var h=e[f+k];e[f+k]=e[f+d];e[f+d]=h;d--}}}function h(a,b,c){c=void 0===c?0:c;for(var g=0,e=a.length;g<e;g++){var d=a.codePointAt(g);if(128>d)b[c]=d,
c++;else{var f=0,k=0;2047>=d?(f=1,k=192):65535>=d?(f=2,k=224):1114111>=d&&(f=3,k=240,g++);b[c]=(d>>6*f)+k;for(c++;0<f;)b[c]=128|d>>6*(f-1)&63,c++,f--}}return c}function l(a){var b=Math.floor(a);a-=b;return.5>a?b:.5<a?b+1:b%2?b+1:b}function n(a,b,c){c=void 0===c?a.length:c;var g=void 0===b?0:b;c=void 0===c?a.length:c;b="";for(g=void 0===g?0:g;g<c;){var d=128,e=191,f=!1,k=a[g++];if(0<=k&&127>=k)b+=String.fromCharCode(k);else{var h=0;194<=k&&223>=k?h=1:224<=k&&239>=k?(h=2,224===a[g]&&(d=160),237===a[g]&&
(e=159)):240<=k&&244>=k?(h=3,240===a[g]&&(d=144),244===a[g]&&(e=143)):f=!0;k&=(1<<8-h-1)-1;for(var l=0;l<h;l++){if(a[g]<d||a[g]>e)f=!0;k=k<<6|a[g]&63;g++}f?b+=String.fromCharCode(65533):65535>=k?b+=String.fromCharCode(k):(k-=65536,b+=String.fromCharCode((k>>10&1023)+55296,(k&1023)+56320))}}return b}function q(a){var b=[];h(a,b,0);return b}function z(a,b,c){return h(a,b,void 0===c?0:c)}function A(a,b,c,g){a=[a];g=void 0===g?0:g;g=void 0===g?0:g;b=b||{};var d=new w(b.bits,b.fp,b.signed),e=0,h=g;try{for(var k=
a.length;e<k;e++)g=d.pack(c,a[e],g);b.be&&f(c,d.offset,h,g)}catch(C){B(C,a[e],e)}return g}function e(a,b){var c=[];A(a,b,c);return c}function y(a,b,c){var g=c=void 0===c?0:c,d=c+Math.ceil(b.bits/8),e=!0;d=void 0===d?a.length:d;c=[];g=void 0===g?0:g;var h=void 0===e?!1:e;g=void 0===g?0:g;d=void 0===d?a.length:d;h=void 0===h?!1:h;b=b||{};e=new w(b.bits,b.fp,b.signed);var k=e.offset,l=(d-g)%k;if(h&&(l||a.length<k))throw Error("Bad buffer length");d-=l;h=0;l=g;try{for(b.be&&f(a,k,g,d);l<d;l+=k,h++)c[h]=
e.unpack(a,l);b.be&&f(a,k,g,d)}catch(D){B(D,a.slice(l,l+k),l)}return c[0]}function B(a,b,c){a.message=a.constructor.name+" at index "+c+": "+b;throw a;}function r(a,b,c){c=void 0===c?!0:c;a=q(a);if(c)for(c=a.length;c<b;c++)a.push(0);return a}var v=function(a,b){this.ebits=a;this.fbits=b;this.bias=(1<<a-1)-1;this.numBytes=Math.ceil((a+b)/8);this.biasP2=Math.pow(2,this.bias+1);this.ebitsFbits=a+b;this.fbias=Math.pow(2,-(8*this.numBytes-1-a))};v.prototype.pack=function(a,b,c){if("number"!=typeof b)throw new TypeError;
Math.abs(b)>this.biasP2-2*this.ebitsFbits&&(b=0>b?-Infinity:Infinity);var g=0>((b=+b)||1/b)?1:0>b?1:0;b=Math.abs(b);var d=Math.min(Math.floor(Math.log(b)/Math.LN2),1023),e=l(b/Math.pow(2,d)*Math.pow(2,this.fbits));b!==b?(e=Math.pow(2,this.fbits-1),d=(1<<this.ebits)-1):0!==b&&(b>=Math.pow(2,1-this.bias)?(2<=e/Math.pow(2,this.fbits)&&(d+=1,e=1),d>this.bias?(d=(1<<this.ebits)-1,e=0):(d+=this.bias,e=l(e)-Math.pow(2,this.fbits))):(e=l(b/Math.pow(2,1-this.bias-this.fbits)),d=0));return this.packFloatBits_(a,
c,g,d,e)};v.prototype.unpack=function(a,b){for(var c=(1<<this.ebits)-1,d="",e=this.numBytes-1;0<=e;e--){var f=a[e+b].toString(2);d+="00000000".substring(f.length)+f}e="1"==d.charAt(0)?-1:1;d=d.substring(1);f=parseInt(d.substring(0,this.ebits),2);d=d.substring(this.ebits);if(f==c)return 0!==parseInt(d,2)?NaN:Infinity*e;0===f?(f+=1,c=parseInt(d,2)):c=parseInt("1"+d,2);return e*c*this.fbias*Math.pow(2,f-this.bias)};v.prototype.packFloatBits_=function(a,b,c,d,e){var g=[];g.push(c);for(c=this.ebits;0<
c;--c)g[c]=d%2?1:0,d=Math.floor(d/2);d=g.length;for(c=this.fbits;0<c;--c)g[d+c]=e%2?1:0,e=Math.floor(e/2);e=g.join("");g=this.numBytes+b-1;for(d=b;g>=b;)a[g]=parseInt(e.substring(0,8),2),e=e.substring(8),g--,d++;return d};var t=function(a){this.bits=a;this.bytes=8>a?1:Math.ceil(a/8);this.max=Math.pow(2,a)-1;this.min=0;a=8-((a-1|7)+1-a);this.lastByteMask_=Math.pow(2,0<a?a:8)-1};t.prototype.pack=function(a,b,c){c=void 0===c?0:c;if(b!==b||"number"!=typeof b)throw new TypeError;this.overflow(b);return this.pack_(a,
b,c)};t.prototype.packUnsafe=function(a,b,c){return this.pack_(a,b,void 0===c?0:c)};t.prototype.unpack=function(a,b){var c=this.unpackUnsafe(a,void 0===b?0:b);this.overflow(c);return c};t.prototype.unpackUnsafe=function(a,b){b=void 0===b?0:b;for(var c=0,d=0;d<this.bytes;d++)c+=a[b+d]*Math.pow(256,d);return c};t.prototype.overflow=function(a){if(a>this.max||a<this.min)throw new RangeError;};t.prototype.pack_=function(a,b,c){c=void 0===c?0:c;a[c]=(0>b?b+Math.pow(2,this.bits):b)&255;c++;for(var d=this.bytes,
e=2;e<d;e++)a[c]=Math.floor(b/Math.pow(2,8*(e-1)))&255,c++;8<this.bits&&(a[c]=Math.floor(b/Math.pow(2,8*(this.bytes-1)))&this.lastByteMask_,c++);return c};var x=function(a){a=t.call(this,a)||this;a.max=Math.pow(2,a.bits)/2-1;a.min=-a.max-1;return a};$jscomp.inherits(x,t);x.prototype.pack=function(a,b,c){return t.prototype.pack.call(this,a,b,void 0===c?0:c)};x.prototype.unpack=function(a,b){var c=t.prototype.unpackUnsafe.call(this,a,void 0===b?0:b);c=this.sign_(c);this.overflow(c);return c};x.prototype.sign_=
function(a){a>this.max&&(a-=2*this.max+2);return a};var w=function(a,b,c){if(b){if(!a||16!==a&&32!==a&&64!==a)throw Error("Unsupported type: float, bits: "+a);b=this.getFPParser_(a)}else{if(!a||1>a||53<a)throw Error("Unsupported type: int, bits: "+a);b=c?new x(a):new t(a)}this.parser=b;this.offset=Math.ceil(a/8)};w.prototype.unpack=function(a,b){return this.parser.unpack(a,void 0===b?0:b)};w.prototype.pack=function(a,b,c){return this.parser.pack(a,b,void 0===c?0:c)};w.prototype.getFPParser_=function(a){return 16===
a?new v(5,11):32===a?new v(8,23):new v(11,52)};var u=function(){this.container="";this.chunkSize=0;this.format="";this.signature=null;this.head=0;this.uInt32={bits:32,be:!1,signed:!1,fp:!1};this.supported_containers=["RIFF","RIFX"]};u.prototype.setSignature=function(a){this.head=0;this.container=this.readString(a,4);if(-1===this.supported_containers.indexOf(this.container))throw Error("Not a supported format.");this.uInt32.be="RIFX"===this.container;this.chunkSize=this.readUInt32(a);this.format=this.readString(a,
4);this.signature={chunkId:this.container,chunkSize:this.chunkSize,format:this.format,subChunks:this.getSubChunksIndex_(a),chunkData:{start:0,end:this.chunkSize}}};u.prototype.findChunk=function(a,b){b=void 0===b?!1:b;for(var c=this.signature.subChunks,d=[],e=0;e<c.length;e++)if(c[e].chunkId==a)if(b)d.push(c[e]);else return c[e];return"LIST"==a?d.length?d:null:null};u.prototype.readString=function(a,b){var c=n(a,this.head,this.head+b);this.head+=b;return c};u.prototype.readUInt32=function(a){a=y(a,
this.uInt32,this.head);this.head+=4;return a};u.prototype.getSubChunksIndex_=function(a){for(var b=[],c=this.head;c<=a.length-8;)b.push(this.getSubChunkIndex_(a,c)),c+=8+b[b.length-1].chunkSize,c=c%2?c+1:c;return b};u.prototype.getSubChunkIndex_=function(a,b){var c={chunkId:this.getChunkId_(a,b),chunkSize:this.getChunkSize_(a,b)};"LIST"==c.chunkId?(c.format=n(a,b+8,b+12),this.head+=4,c.subChunks=this.getSubChunksIndex_(a)):(this.head=b+8+(c.chunkSize%2?c.chunkSize+1:c.chunkSize),c.chunkData={start:b+
8,end:this.head});return c};u.prototype.getChunkId_=function(a,b){this.head+=4;return n(a,b,b+4)};u.prototype.getChunkSize_=function(a,b){this.head+=4;return y(a,this.uInt32,b+4)};var m=function(a,b){a=void 0===a?null:a;b=void 0===b?!0:b;var c=u.call(this)||this;c.supported_containers.push("RF64");c.fmt={chunkId:"",chunkSize:0,audioFormat:0,numChannels:0,sampleRate:0,byteRate:0,blockAlign:0,bitsPerSample:0,cbSize:0,validBitsPerSample:0,dwChannelMask:0,subformat:[]};c.fact={chunkId:"",chunkSize:0,
dwSampleLength:0};c.cue={chunkId:"",chunkSize:0,dwCuePoints:0,points:[]};c.smpl={chunkId:"",chunkSize:0,dwManufacturer:0,dwProduct:0,dwSamplePeriod:0,dwMIDIUnityNote:0,dwMIDIPitchFraction:0,dwSMPTEFormat:0,dwSMPTEOffset:0,dwNumSampleLoops:0,dwSamplerData:0,loops:[]};c.bext={chunkId:"",chunkSize:0,description:"",originator:"",originatorReference:"",originationDate:"",originationTime:"",timeReference:[0,0],version:0,UMID:"",loudnessValue:0,loudnessRange:0,maxTruePeakLevel:0,maxMomentaryLoudness:0,maxShortTermLoudness:0,
reserved:"",codingHistory:""};c.ds64={chunkId:"",chunkSize:0,riffSizeHigh:0,riffSizeLow:0,dataSizeHigh:0,dataSizeLow:0,originationTime:0,sampleCountHigh:0,sampleCountLow:0};c.data={chunkId:"",chunkSize:0,samples:new Uint8Array(0)};c.LIST=[];c.junk={chunkId:"",chunkSize:0,chunkData:[]};c.uInt16={bits:16,be:!1,signed:!1,fp:!1};a&&c.fromBuffer(a,b);return c};$jscomp.inherits(m,u);m.prototype.fromBuffer=function(a,b){b=void 0===b?!0:b;this.clearHeaders();this.setSignature(a);this.uInt16.be=this.uInt32.be;
if("WAVE"!=this.format)throw Error('Could not find the "WAVE" format identifier');this.readDs64Chunk_(a);this.readFmtChunk_(a);this.readFactChunk_(a);this.readBextChunk_(a);this.readCueChunk_(a);this.readSmplChunk_(a);this.readDataChunk_(a,b);this.readJunkChunk_(a);this.readLISTChunk_(a)};m.prototype.clearHeaders=function(){var a=new m;Object.assign(this.fmt,a.fmt);Object.assign(this.fact,a.fact);Object.assign(this.cue,a.cue);Object.assign(this.smpl,a.smpl);Object.assign(this.bext,a.bext);Object.assign(this.ds64,
a.ds64);Object.assign(this.data,a.data);this.LIST=[];Object.assign(this.junk,a.junk)};m.prototype.readFmtChunk_=function(a){var b=this.findChunk("fmt ");if(b)this.head=b.chunkData.start,this.fmt.chunkId=b.chunkId,this.fmt.chunkSize=b.chunkSize,this.fmt.audioFormat=this.readUInt16_(a),this.fmt.numChannels=this.readUInt16_(a),this.fmt.sampleRate=this.readUInt32(a),this.fmt.byteRate=this.readUInt32(a),this.fmt.blockAlign=this.readUInt16_(a),this.fmt.bitsPerSample=this.readUInt16_(a),this.readFmtExtension_(a);
else throw Error('Could not find the "fmt " chunk');};m.prototype.readFmtExtension_=function(a){16<this.fmt.chunkSize&&(this.fmt.cbSize=this.readUInt16_(a),18<this.fmt.chunkSize&&(this.fmt.validBitsPerSample=this.readUInt16_(a),20<this.fmt.chunkSize&&(this.fmt.dwChannelMask=this.readUInt32(a),this.fmt.subformat=[this.readUInt32(a),this.readUInt32(a),this.readUInt32(a),this.readUInt32(a)])))};m.prototype.readFactChunk_=function(a){var b=this.findChunk("fact");b&&(this.head=b.chunkData.start,this.fact.chunkId=
b.chunkId,this.fact.chunkSize=b.chunkSize,this.fact.dwSampleLength=this.readUInt32(a))};m.prototype.readCueChunk_=function(a){var b=this.findChunk("cue ");if(b)for(this.head=b.chunkData.start,this.cue.chunkId=b.chunkId,this.cue.chunkSize=b.chunkSize,this.cue.dwCuePoints=this.readUInt32(a),b=0;b<this.cue.dwCuePoints;b++)this.cue.points.push({dwName:this.readUInt32(a),dwPosition:this.readUInt32(a),fccChunk:this.readString(a,4),dwChunkStart:this.readUInt32(a),dwBlockStart:this.readUInt32(a),dwSampleOffset:this.readUInt32(a)})};
m.prototype.readSmplChunk_=function(a){var b=this.findChunk("smpl");if(b)for(this.head=b.chunkData.start,this.smpl.chunkId=b.chunkId,this.smpl.chunkSize=b.chunkSize,this.smpl.dwManufacturer=this.readUInt32(a),this.smpl.dwProduct=this.readUInt32(a),this.smpl.dwSamplePeriod=this.readUInt32(a),this.smpl.dwMIDIUnityNote=this.readUInt32(a),this.smpl.dwMIDIPitchFraction=this.readUInt32(a),this.smpl.dwSMPTEFormat=this.readUInt32(a),this.smpl.dwSMPTEOffset=this.readUInt32(a),this.smpl.dwNumSampleLoops=this.readUInt32(a),
this.smpl.dwSamplerData=this.readUInt32(a),b=0;b<this.smpl.dwNumSampleLoops;b++)this.smpl.loops.push({dwName:this.readUInt32(a),dwType:this.readUInt32(a),dwStart:this.readUInt32(a),dwEnd:this.readUInt32(a),dwFraction:this.readUInt32(a),dwPlayCount:this.readUInt32(a)})};m.prototype.readDataChunk_=function(a,b){var c=this.findChunk("data");if(c)this.data.chunkId="data",this.data.chunkSize=c.chunkSize,b&&(this.data.samples=a.slice(c.chunkData.start,c.chunkData.end));else throw Error('Could not find the "data" chunk');
};m.prototype.readBextChunk_=function(a){var b=this.findChunk("bext");b&&(this.head=b.chunkData.start,this.bext.chunkId=b.chunkId,this.bext.chunkSize=b.chunkSize,this.bext.description=this.readString(a,256),this.bext.originator=this.readString(a,32),this.bext.originatorReference=this.readString(a,32),this.bext.originationDate=this.readString(a,10),this.bext.originationTime=this.readString(a,8),this.bext.timeReference=[this.readUInt32(a),this.readUInt32(a)],this.bext.version=this.readUInt16_(a),this.bext.UMID=
this.readString(a,64),this.bext.loudnessValue=this.readUInt16_(a),this.bext.loudnessRange=this.readUInt16_(a),this.bext.maxTruePeakLevel=this.readUInt16_(a),this.bext.maxMomentaryLoudness=this.readUInt16_(a),this.bext.maxShortTermLoudness=this.readUInt16_(a),this.bext.reserved=this.readString(a,180),this.bext.codingHistory=this.readString(a,this.bext.chunkSize-602))};m.prototype.readDs64Chunk_=function(a){var b=this.findChunk("ds64");if(b)this.head=b.chunkData.start,this.ds64.chunkId=b.chunkId,this.ds64.chunkSize=
b.chunkSize,this.ds64.riffSizeHigh=this.readUInt32(a),this.ds64.riffSizeLow=this.readUInt32(a),this.ds64.dataSizeHigh=this.readUInt32(a),this.ds64.dataSizeLow=this.readUInt32(a),this.ds64.originationTime=this.readUInt32(a),this.ds64.sampleCountHigh=this.readUInt32(a),this.ds64.sampleCountLow=this.readUInt32(a);else if("RF64"==this.container)throw Error('Could not find the "ds64" chunk');};m.prototype.readLISTChunk_=function(a){var b=this.findChunk("LIST",!0);if(null!==b)for(var c=0;c<b.length;c++){var d=
b[c];this.LIST.push({chunkId:d.chunkId,chunkSize:d.chunkSize,format:d.format,subChunks:[]});for(var e=0;e<d.subChunks.length;e++)this.readLISTSubChunks_(d.subChunks[e],d.format,a)}};m.prototype.readLISTSubChunks_=function(a,b,c){"adtl"==b?-1<["labl","note","ltxt"].indexOf(a.chunkId)&&(this.head=a.chunkData.start,b={chunkId:a.chunkId,chunkSize:a.chunkSize,dwName:this.readUInt32(c)},"ltxt"==a.chunkId&&(b.dwSampleLength=this.readUInt32(c),b.dwPurposeID=this.readUInt32(c),b.dwCountry=this.readUInt16_(c),
b.dwLanguage=this.readUInt16_(c),b.dwDialect=this.readUInt16_(c),b.dwCodePage=this.readUInt16_(c)),b.value=this.readZSTR_(c,this.head),this.LIST[this.LIST.length-1].subChunks.push(b)):"INFO"==b&&(this.head=a.chunkData.start,this.LIST[this.LIST.length-1].subChunks.push({chunkId:a.chunkId,chunkSize:a.chunkSize,value:this.readZSTR_(c,this.head)}))};m.prototype.readJunkChunk_=function(a){var b=this.findChunk("junk");b&&(this.junk={chunkId:b.chunkId,chunkSize:b.chunkSize,chunkData:[].slice.call(a.slice(b.chunkData.start,
b.chunkData.end))})};m.prototype.readZSTR_=function(a,b){for(var c=b=void 0===b?0:b;c<a.length&&(this.head++,0!==a[c]);c++);return n(a,b,this.head-1)};m.prototype.readUInt16_=function(a){a=y(a,this.uInt16,this.head);this.head+=2;return a};var p=function(){return m.apply(this,arguments)||this};$jscomp.inherits(p,m);p.prototype.toBuffer=function(){this.uInt16.be="RIFX"===this.container;this.uInt32.be=this.uInt16.be;for(var a=[this.getJunkBytes_(),this.getDs64Bytes_(),this.getBextBytes_(),this.getFmtBytes_(),
this.getFactBytes_(),q(this.data.chunkId),e(this.data.samples.length,this.uInt32),this.data.samples,this.getCueBytes_(),this.getSmplBytes_(),this.getLISTBytes_()],b=0,c=0;c<a.length;c++)b+=a[c].length;c=new Uint8Array(b+12);var d=z(this.container,c,0);d=A(b+4,this.uInt32,c,d);d=z(this.format,c,d);for(b=0;b<a.length;b++)c.set(a[b],d),d+=a[b].length;return c};p.prototype.getBextBytes_=function(){var a=[];this.enforceBext_();this.bext.chunkId&&(this.bext.chunkSize=602+this.bext.codingHistory.length,
a=a.concat(q(this.bext.chunkId),e(602+this.bext.codingHistory.length,this.uInt32),r(this.bext.description,256),r(this.bext.originator,32),r(this.bext.originatorReference,32),r(this.bext.originationDate,10),r(this.bext.originationTime,8),e(this.bext.timeReference[0],this.uInt32),e(this.bext.timeReference[1],this.uInt32),e(this.bext.version,this.uInt16),r(this.bext.UMID,64),e(this.bext.loudnessValue,this.uInt16),e(this.bext.loudnessRange,this.uInt16),e(this.bext.maxTruePeakLevel,this.uInt16),e(this.bext.maxMomentaryLoudness,
this.uInt16),e(this.bext.maxShortTermLoudness,this.uInt16),r(this.bext.reserved,180),r(this.bext.codingHistory,this.bext.codingHistory.length)));a.length%2&&a.push(0);return a};p.prototype.enforceBext_=function(){for(var a in this.bext)if(this.bext.hasOwnProperty(a)&&this.bext[a]&&"timeReference"!=a){this.bext.chunkId="bext";break}if(this.bext.timeReference[0]||this.bext.timeReference[1])this.bext.chunkId="bext"};p.prototype.getDs64Bytes_=function(){var a=[];this.ds64.chunkId&&(a=a.concat(q(this.ds64.chunkId),
e(this.ds64.chunkSize,this.uInt32),e(this.ds64.riffSizeHigh,this.uInt32),e(this.ds64.riffSizeLow,this.uInt32),e(this.ds64.dataSizeHigh,this.uInt32),e(this.ds64.dataSizeLow,this.uInt32),e(this.ds64.originationTime,this.uInt32),e(this.ds64.sampleCountHigh,this.uInt32),e(this.ds64.sampleCountLow,this.uInt32)));return a};p.prototype.getCueBytes_=function(){var a=[];if(this.cue.chunkId){var b=this.getCuePointsBytes_();a=a.concat(q(this.cue.chunkId),e(b.length+4,this.uInt32),e(this.cue.dwCuePoints,this.uInt32),
b)}return a};p.prototype.getCuePointsBytes_=function(){for(var a=[],b=0;b<this.cue.dwCuePoints;b++)a=a.concat(e(this.cue.points[b].dwName,this.uInt32),e(this.cue.points[b].dwPosition,this.uInt32),q(this.cue.points[b].fccChunk),e(this.cue.points[b].dwChunkStart,this.uInt32),e(this.cue.points[b].dwBlockStart,this.uInt32),e(this.cue.points[b].dwSampleOffset,this.uInt32));return a};p.prototype.getSmplBytes_=function(){var a=[];if(this.smpl.chunkId){var b=this.getSmplLoopsBytes_();a=a.concat(q(this.smpl.chunkId),
e(b.length+36,this.uInt32),e(this.smpl.dwManufacturer,this.uInt32),e(this.smpl.dwProduct,this.uInt32),e(this.smpl.dwSamplePeriod,this.uInt32),e(this.smpl.dwMIDIUnityNote,this.uInt32),e(this.smpl.dwMIDIPitchFraction,this.uInt32),e(this.smpl.dwSMPTEFormat,this.uInt32),e(this.smpl.dwSMPTEOffset,this.uInt32),e(this.smpl.dwNumSampleLoops,this.uInt32),e(this.smpl.dwSamplerData,this.uInt32),b)}return a};p.prototype.getSmplLoopsBytes_=function(){for(var a=[],b=0;b<this.smpl.dwNumSampleLoops;b++)a=a.concat(e(this.smpl.loops[b].dwName,
this.uInt32),e(this.smpl.loops[b].dwType,this.uInt32),e(this.smpl.loops[b].dwStart,this.uInt32),e(this.smpl.loops[b].dwEnd,this.uInt32),e(this.smpl.loops[b].dwFraction,this.uInt32),e(this.smpl.loops[b].dwPlayCount,this.uInt32));return a};p.prototype.getFactBytes_=function(){var a=[];this.fact.chunkId&&(a=a.concat(q(this.fact.chunkId),e(this.fact.chunkSize,this.uInt32),e(this.fact.dwSampleLength,this.uInt32)));return a};p.prototype.getFmtBytes_=function(){var a=[];if(this.fmt.chunkId)return a.concat(q(this.fmt.chunkId),
e(this.fmt.chunkSize,this.uInt32),e(this.fmt.audioFormat,this.uInt16),e(this.fmt.numChannels,this.uInt16),e(this.fmt.sampleRate,this.uInt32),e(this.fmt.byteRate,this.uInt32),e(this.fmt.blockAlign,this.uInt16),e(this.fmt.bitsPerSample,this.uInt16),this.getFmtExtensionBytes_());throw Error('Could not find the "fmt " chunk');};p.prototype.getFmtExtensionBytes_=function(){var a=[];16<this.fmt.chunkSize&&(a=a.concat(e(this.fmt.cbSize,this.uInt16)));18<this.fmt.chunkSize&&(a=a.concat(e(this.fmt.validBitsPerSample,
this.uInt16)));20<this.fmt.chunkSize&&(a=a.concat(e(this.fmt.dwChannelMask,this.uInt32)));24<this.fmt.chunkSize&&(a=a.concat(e(this.fmt.subformat[0],this.uInt32),e(this.fmt.subformat[1],this.uInt32),e(this.fmt.subformat[2],this.uInt32),e(this.fmt.subformat[3],this.uInt32)));return a};p.prototype.getLISTBytes_=function(){for(var a=[],b=0;b<this.LIST.length;b++){var c=this.getLISTSubChunksBytes_(this.LIST[b].subChunks,this.LIST[b].format);a=a.concat(q(this.LIST[b].chunkId),e(c.length+4,this.uInt32),
q(this.LIST[b].format),c)}return a};p.prototype.getLISTSubChunksBytes_=function(a,b){for(var c=[],d=0;d<a.length;d++)"INFO"==b?(c=c.concat(q(a[d].chunkId),e(a[d].value.length+1,this.uInt32),r(a[d].value,a[d].value.length)),c.push(0)):"adtl"==b&&(-1<["labl","note"].indexOf(a[d].chunkId)?(c=c.concat(q(a[d].chunkId),e(a[d].value.length+4+1,this.uInt32),e(a[d].dwName,this.uInt32),r(a[d].value,a[d].value.length)),c.push(0)):"ltxt"==a[d].chunkId&&(c=c.concat(this.getLtxtChunkBytes_(a[d])))),c.length%2&&
c.push(0);return c};p.prototype.getLtxtChunkBytes_=function(a){return[].concat(q(a.chunkId),e(a.value.length+20,this.uInt32),e(a.dwName,this.uInt32),e(a.dwSampleLength,this.uInt32),e(a.dwPurposeID,this.uInt32),e(a.dwCountry,this.uInt16),e(a.dwLanguage,this.uInt16),e(a.dwDialect,this.uInt16),e(a.dwCodePage,this.uInt16),r(a.value,a.value.length))};p.prototype.getJunkBytes_=function(){var a=[];return this.junk.chunkId?a.concat(q(this.junk.chunkId),e(this.junk.chunkData.length,this.uInt32),this.junk.chunkData):
a};d.WaveFileParser=p;Object.defineProperty(d,"__esModule",{value:!0})});
